### PR TITLE
Update runtime, application, add libcanberra, patch for building

### LINKED ISSUE #4: This uses an EOL'd runtime.
This relies on GNOME runtime 3.36 which was EOL'd in February 2021. If it can't be built against runtime 40, could 3.38 be used instead?

### PR DESCRIPTION
**Pull request by lionirdeadman**

### CODE REVIEW

**Comment by bilelmoussaoui** [comment]
Sorry for taking too long to review, i suppose those patches were submitted upstream already?

**Comment by lionirdeadman** [comment]
Yeah, they're in upstream git

https://gitlab.gnome.org/GNOME/gnome-taquin/-/commit/66be44dc20d114e449fc33156e3939fd05dfbb16
https://gitlab.gnome.org/GNOME/gnome-taquin/-/commit/99dea5e7863e112f33f16e59898c56a4f1a547b3

**Comment by bilelmoussaoui** [comment]
Thanks !

**Comment by neildarlow** [comment]
@bilelmoussaoui Nice, thank you!

**Comment by neildarlow** [comment]
When will this become live? An install still pulls-in Platform 3.36.

Thanks.

**Comment by wjt** [comment]
I just triggered a successful rebuild. (Previously GitHub was showing the tip of master as building, now, green.) Publishing now.

**Pull request merged**
